"""Initial database schema

Revision ID: 02697d04ce8f
Revises: 
Create Date: 2025-12-31 15:41:25.780527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02697d04ce8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('favorite_campgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('campground_id', sa.String(length=50), nullable=False),
    sa.Column('campground_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_favorite_campgrounds_user_id', 'favorite_campgrounds', ['user_id'], unique=False)
    op.create_index('idx_favorite_unique', 'favorite_campgrounds', ['user_id', 'provider', 'campground_id'], unique=True)
    op.create_index(op.f('ix_favorite_campgrounds_id'), 'favorite_campgrounds', ['id'], unique=False)
    op.create_table('monitoring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('campground_id', sa.String(length=50), nullable=False),
    sa.Column('campground_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('search_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rq_job_id', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_monitoring_tasks_active', 'monitoring_tasks', ['user_id', 'status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_monitoring_tasks_status', 'monitoring_tasks', ['status'], unique=False)
    op.create_index('idx_monitoring_tasks_user_id', 'monitoring_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_monitoring_tasks_id'), 'monitoring_tasks', ['id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_settings_user_type', 'notification_settings', ['user_id', 'notification_type'], unique=True)
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('campground_name', sa.String(length=255), nullable=False),
    sa.Column('availability_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['monitoring_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_history_sent_at', 'notification_history', ['sent_at'], unique=False, postgresql_using='btree', postgresql_ops={'sent_at': 'DESC'})
    op.create_index('idx_notification_history_user_id', 'notification_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_history_id'), 'notification_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_history_id'), table_name='notification_history')
    op.drop_index('idx_notification_history_user_id', table_name='notification_history')
    op.drop_index('idx_notification_history_sent_at', table_name='notification_history', postgresql_using='btree', postgresql_ops={'sent_at': 'DESC'})
    op.drop_table('notification_history')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_index('idx_notification_settings_user_type', table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_monitoring_tasks_id'), table_name='monitoring_tasks')
    op.drop_index('idx_monitoring_tasks_user_id', table_name='monitoring_tasks')
    op.drop_index('idx_monitoring_tasks_status', table_name='monitoring_tasks')
    op.drop_index('idx_monitoring_tasks_active', table_name='monitoring_tasks', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('monitoring_tasks')
    op.drop_index(op.f('ix_favorite_campgrounds_id'), table_name='favorite_campgrounds')
    op.drop_index('idx_favorite_unique', table_name='favorite_campgrounds')
    op.drop_index('idx_favorite_campgrounds_user_id', table_name='favorite_campgrounds')
    op.drop_table('favorite_campgrounds')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
